name: "VPC CI"

on:
    push:
        paths:
            - "sanbox/sandbox.tf"
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    terraform-plan:
        name: "Terraform Plan"
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./sanbox

        env:
            AWS_REGION: "us-east-1"
            TF_LOG: INFO

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "AWS creds - OIDC"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::514005485562:role/GitHubActionsTerraformRole
                  aws-region: ${{ env.AWS_REGION }}

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.11.0"

            - name: "Terraform init"
              id: init
              run: terraform init

            - name: "Terraform Plan"
              id: plan
              run: terraform plan -input=false -no-color -out=tfplan

            - name: "Install tf-summarize and print"
              run: |
                  curl -sSL "https://github.com/dineshba/tf-summarize/releases/latest/download/tf-summarize_linux_amd64.tar.gz" | tar -xz
                  sudo mv tf-summarize /usr/local/bin/

                  echo "=== Terraform Plan Summary ==="
                  env TF_LOG= terraform show -json tfplan | tf-summarize

            - name: "terraform plan upload"
              uses: actions/upload-artifact@v4
              with:
                  name: tfplan
                  path: ./sanbox/tfplan
                  retention-days: 1

    terraform-apply:
        name: "Terraform Apply"
        runs-on: ubuntu-latest
        needs: terraform-plan
        # Only run apply if on main branch or manually triggered
        if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        environment: production

        defaults:
            run:
                working-directory: ./sanbox

        env:
            AWS_REGION: "us-east-1" # Telling github actions to use us-east-1
            TF_LOG: INFO

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v4

            - name: "AWS creds - OIDC"
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: arn:aws:iam::514005485562:role/GitHubActionsTerraformRole
                  # This role must be already created
                  aws-region: ${{ env.AWS_REGION }}

            - name: "Setup Terraform"
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "1.11.0"

            - name: "Download Terraform Plan"
              uses: actions/download-artifact@v4
              with:
                  name: tfplan
                  path: ./sanbox/

            - name: "Terraform init"
              id: init
              run: terraform init

            - name: "Terraform Apply"
              run: terraform apply -input=false -no-color tfplan
